In [2]:
import tensorflow as tf
import pandas as pd

In [3]:
file = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(file)

In [11]:
iris = pd.get_dummies(iris)

In [12]:
iris.columns

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')

In [18]:
cs = iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
rs = iris[['품종_setosa', '품종_versicolor',
       '품종_virginica']]

In [8]:
rs.shape

(150, 1)

In [51]:
X = tf.keras.layers.Input(shape=[4])

H = tf.keras.layers.Dense(5, activation='swish')(X)

H = tf.keras.layers.Dense(8)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [54]:
model.fit(cs, rs, epochs=500) 

Epoch 1/500
5/5 [==============================] - 0s 2ms/step - loss: 0.2417 - accuracy: 0.8867
Epoch 2/500
5/5 [==============================] - 0s 3ms/step - loss: 0.2230 - accuracy: 0.9133
Epoch 3/500
5/5 [==============================] - 0s 3ms/step - loss: 0.2060 - accuracy: 0.9200
Epoch 4/500
5/5 [==============================] - 0s 3ms/step - loss: 0.2066 - accuracy: 0.9200
Epoch 5/500
5/5 [==============================] - 0s 3ms/step - loss: 0.2076 - accuracy: 0.9267
Epoch 6/500
5/5 [==============================] - 0s 3ms/step - loss: 0.2108 - accuracy: 0.9200
Epoch 7/500
5/5 [==============================] - 0s 3ms/step - loss: 0.2000 - accuracy: 0.9133
Epoch 8/500
5/5 [==============================] - 0s 3ms/step - loss: 0.2194 - accuracy: 0.9267
Epoch 9/500
5/5 [==============================] - 0s 2ms/step - loss: 0.1889 - accuracy: 0.9267
Epoch 10/500
5/5 [==============================] - 0s 3ms/step - loss: 0.1858 - accuracy: 0.9333
Epoch 11/500
5/5 [===========

In [41]:
cs

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭
0     5.1  3.5    1.4   0.2
1     4.9  3.0    1.4   0.2
2     4.7  3.2    1.3   0.2
3     4.6  3.1    1.5   0.2
4     5.0  3.6    1.4   0.2
..    ...  ...    ...   ...
145   6.7  3.0    5.2   2.3
146   6.3  2.5    5.0   1.9
147   6.5  3.0    5.2   2.0
148   6.2  3.4    5.4   2.3
149   5.9  3.0    5.1   1.8

[150 rows x 4 columns]

In [55]:
model.predict(cs[0:50])

array([[1.0000000e+00, 5.4630946e-11, 1.3793838e-10],
       [1.0000000e+00, 1.2370880e-09, 1.0511297e-08],
       [1.0000000e+00, 2.5463540e-10, 4.9503840e-10],
       [1.0000000e+00, 2.8759771e-08, 6.5433028e-09],
       [1.0000000e+00, 5.7470351e-11, 4.6690461e-11],
       [1.0000000e+00, 1.6404273e-08, 1.4313342e-10],
       [1.0000000e+00, 7.0462316e-09, 1.3116186e-10],
       [1.0000000e+00, 7.7306828e-10, 7.6084350e-10],
       [1.0000000e+00, 3.3021703e-08, 1.2689448e-08],
       [1.0000000e+00, 1.1360064e-09, 9.0253236e-09],
       [1.0000000e+00, 3.2361593e-11, 8.0747929e-11],
       [1.0000000e+00, 1.9675630e-08, 1.5480908e-09],
       [1.0000000e+00, 5.6844401e-10, 8.2991019e-09],
       [1.0000000e+00, 4.3722890e-11, 2.9673863e-10],
       [1.0000000e+00, 3.4269184e-14, 3.8030638e-13],
       [1.0000000e+00, 6.2975341e-12, 2.3634171e-13],
       [1.0000000e+00, 5.5803916e-12, 1.6353381e-12],
       [1.0000000e+00, 2.0556326e-10, 1.2774601e-10],
       [1.0000000e+00, 5.959

In [56]:
model.predict(cs[51:100])

array([[9.89634555e-06, 9.99497414e-01, 4.92741703e-04],
       [1.43844891e-05, 9.96314704e-01, 3.67095089e-03],
       [4.56398593e-05, 9.99249637e-01, 7.04656763e-04],
       [2.31712020e-05, 9.96644378e-01, 3.33253364e-03],
       [2.52320788e-05, 9.98162329e-01, 1.81251578e-03],
       [2.48416236e-05, 9.93658364e-01, 6.31678151e-03],
       [1.69399973e-05, 9.99978185e-01, 4.92799654e-06],
       [7.43221153e-06, 9.99705851e-01, 2.86787195e-04],
       [3.77803844e-05, 9.99578655e-01, 3.83582723e-04],
       [5.03703741e-05, 9.99900103e-01, 4.94619271e-05],
       [1.73676217e-05, 9.99573052e-01, 4.09502158e-04],
       [1.87747319e-05, 9.99916911e-01, 6.42595987e-05],
       [2.69711818e-05, 9.94485676e-01, 5.48725994e-03],
       [6.39069913e-06, 9.99987364e-01, 6.24733366e-06],
       [4.35461698e-06, 9.99911904e-01, 8.36508334e-05],
       [5.02297698e-05, 9.87979412e-01, 1.19703859e-02],
       [4.71142448e-06, 9.99978900e-01, 1.63133591e-05],
       [8.43389280e-05, 9.35229

In [57]:
model.predict(cs[101:150])

array([[2.07712205e-07, 4.50887578e-03, 9.95490968e-01],
       [4.97487207e-09, 6.73278410e-04, 9.99326706e-01],
       [8.86793927e-08, 3.32183391e-03, 9.96678114e-01],
       [8.52165949e-10, 2.63301859e-04, 9.99736726e-01],
       [9.72317712e-11, 8.87320639e-05, 9.99911308e-01],
       [9.25039694e-06, 4.11362797e-02, 9.58854437e-01],
       [5.79110937e-09, 7.32353306e-04, 9.99267638e-01],
       [1.34088429e-08, 1.10731216e-03, 9.98892725e-01],
       [2.25654953e-10, 1.32417597e-04, 9.99867558e-01],
       [3.50039841e-06, 4.78972346e-02, 9.52099323e-01],
       [2.17953541e-07, 5.62244980e-03, 9.94377315e-01],
       [4.90816490e-08, 2.35659000e-03, 9.97643292e-01],
       [6.68427660e-08, 1.88195752e-03, 9.98118043e-01],
       [2.31777220e-09, 3.38924845e-04, 9.99661088e-01],
       [2.11838103e-08, 1.31897884e-03, 9.98681009e-01],
       [5.20309300e-07, 1.15762865e-02, 9.88423169e-01],
       [3.25615618e-10, 1.59223899e-04, 9.99840736e-01],
       [5.81171125e-13, 6.04132